<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students[
	<!ELEMENT students (student+)>
	<!ELEMENT student (name, age, sex)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT age  (#PCDATA)>
	<!ELEMENT sex  (#PCDATA)>
]>



<students>

    <student>
        <name>Zhangsan</name>
        <age>22</age>
        <sex>male</sex>
    </student>
    <student>
        <name>Lisi</name>
        <age>21</age>
        <sex>female</sex>
    </student>
</students>
